apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-go03
  namespace: go03
  labels:
    app: go03
spec:
  selector:
    matchLabels:
      app: go03
  template:
    metadata:
      labels:
        app: go03
    spec:
      imagePullSecrets:
        - name: ghcr-cs 
      terminationGracePeriodSeconds: 30
      containers:
      - name: gk03-app
        image: ghcr.io/comboshreddies/humboldthain-go03:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        lifecycle:
          preStop:
            httpGet:
              path: "/internal/shutdown?off=true"
              port: 8080
        resources:
          requests:
            cpu: 200m
            memory: 300m
          limits:
            cpu: 200m
            memory: 300m
        livenessProbe:
          httpGet:
            path: /internal/live
            port: 8080
        readinessProbe:
          httpGet:
            path: /internal/ready
            port: 8080

