name: getAll-k8s
on: [workflow_dispatch]
jobs:
  getAll-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get all k8s
        env:
          PASSWORD: ${{ secrets.GH_PAT }}
          GKE_TGZ_PASS: ${{ secrets.GKE_TGZ_PASS }}
        run: ./utils/gke_k8s.sh k8s_getAll

