name: run-on-push
on: [push]
jobs:
  run-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make docker image
        run: make docker-image
      - name: run unit test
        run: make test
      - name: run pwd
        run: pwd ; ls
      - name: run docker test
        run: ./docker-test.sh
      - name: login and push
        env:
          PASSWORD: ${{ secrets.GH_PAT }}
        run: ./ghcr-push.sh

